server:
  port: ${PORT:3333}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

spring:
   data:
     mongodb:
       database: mydb
       uri: mongodb+srv://jay:jay@cluster0.1y6t7.mongodb.net/mydb?retryWrites=true&w=majority

ribbon:
  eureka:
    enabled: true